services:
  - type: web
    name: websocket-server
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-123
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    plan: free
    # Добавляем настройки для WebSocket
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type"
      - path: /*
        name: Upgrade
        value: "websocket"
      - path: /*
        name: Connection
        value: "Upgrade" 